### ISSUE TITLE
Implement use of $ref

### ISSUE THREAD

**Issue by matthew-inamdar** [goldspecdigital/oooas#16]
A simple string value may be enough, although if we could do some advanced referencing to the components object, that would be cool.

**Comment by vyuldashev** [comment]
It would be cool, if Schema with ref created is being added to components so it will be reusable.

**Comment by matthew-inamdar** [comment]
@vyuldashev Yeah it would be - it would help keep the size of the response down as well if that is an issue for certain users.

@swumao already did some work on this - so I'll add this in too!

**Comment by vyuldashev** [comment]
@matthew-inamdar Also code generators will generate proper code if we will use components. For example, https://github.com/janephp/janephp will generate Request/Response objects.

**Comment by matthew-inamdar** [comment]
@vyuldashev oh nice, we'll deffo get to work on this.

**Comment by matthew-inamdar** [comment]
Closing as support for ref has been completed and is currently in the `develop` branch with planned release for `v2.2.0`.

@vyuldashev the ability to place schemas in the components section is being tracked in #25 - we're looking at also getting this in the `v2.2.0` release!
