### ISSUE TITLE
Why almost all class method clone $this and return another instance?

### ISSUE THREAD

**Issue by swumao** [goldspecdigital/oooas#21]
Why almost all class method clone $this and return another instance?

Now implementation like this:
```php
    public function description(?string $description): self
    {
        $instance = clone $this;

        $instance->description = $description;

        return $instance;
    }
```

and if I write code like below:
```php
$obj = Schema::create();

// do something ..
$obj->title('test');
```
$obj now have null title attribute.

Why implementation like this?
```php
    public function description(?string $description): self
    {
        $this->description = $description;

        return $this;
    }
```

**Comment by matthew-inamdar** [comment]
Hey @swumao this is to make the objects immutable - so you can't alter the object once they are created, you can only create new ones instead. It will greatly reduce the chance of bugs cropping up when reusing objects. 

The example you gave could be rewritten as follow:

```php
$obj = Schema::create();

// do something ..
$obj = $obj->title('test');
```

**Comment by swumao** [comment]
I know that now, thanks.
