### ISSUE TITLE
How i can upload file?

### ISSUE THREAD

**Issue by hmurich** [goldspecdigital/oooas#43]
Hello. Can you help to me. I don`t understand how i can upload file.  It should be like this https://swagger.io/docs/specification/2-0/file-upload/ ? But i don`t know how i can do this

**Comment by matthew-inamdar** [comment]
Hey @hmurich 👋 

The link you've provided relates to OASv2, however, this package only works with OASv3.

You can achieve this in v3 by specifying the media type in a request body: https://swagger.io/specification/#media-type-object
